### ISSUE TITLE
Infinite redirection loop on login

### ISSUE THREAD

**Issue by Infarinato** [BasLijten/SitecoreFederatedLogin#6]
Thank you for sample solution and nice blog post about Sitecore & AD FS with OWIN, Bas.

I believe I’ve got your solution set up correctly on a fresh Sitecore 8.1 instance, but I’m getting infinitely redirected to SelfSTS (and back to the login page) on login. :-(

(The WSFedTokens database seems to be getting successfully populated, though.)

Am I missing anything obvious? Do the Sitecore application and the “identity provider” (in my case SelfSTS) have to share the same domain?… Or is there a specific claim that your code is expecting?

Many thanks,

Paolo

**Comment by Infarinato** [comment]
Answering my own question, just in case others encounter the same problem —if you are using SelfSTS as your local identity provider to test Bas’s code, make sure the following claims are present:

- http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
- http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
- http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider

(The second and third one relate to [this](https://stack247.wordpress.com/2013/02/22/antiforgerytoken-a-claim-of-type-nameidentifier-or-identityprovider-was-not-present-on-provided-claimsidentity/), whereas I’m not sure whether the first one is a general OWIN requirement or just a SitecoreFederatedLogin implementation one.)

**Comment by BasLijten** [comment]
Hi Infarinato, thanks for adding this Issue. Should I close the issue?

**Comment by Infarinato** [comment]
Sure. 😊 Thank you for replying.

On a completely different note —this is no issue at all, just my lack of understanding—, I’m not entirely clear how you go about redirecting back to any [Authorize]d page other than the login one. Basically, _where_ do you actually override the Wreply that’s set on start-up?

**Comment by BasLijten** [comment]
good one, as we are using a slight different codebase and other approach for login/redirect (although the concept of federation and claims is still the same) I _think_ that we didn't handle the redirect. You should handle this at the moment when you have been redirected from the STS back to Sitecore (in sitecore)
